### ISSUE TITLE
qt5libraries.zip link not working

### ISSUE THREAD

**Issue by beukhof1** [mariusmotea/qtHue#4]
http://mariusmotea.go.ro/Share/qt5libraries.zip

**Comment by mariusmotea** [comment]
Sorry, this is my home server and now i'm migrating to a new provider. Tomorrow will be available again.

Marius.

**Comment by mariusmotea** [comment]
Link is working now

**Comment by pete111** [comment]
hi, link is not working for me. :(

**Comment by mariusmotea** [comment]
sorry, i have a server maintenance work that did not work well. In a few days i will be able to replace the server.
