### ISSUE TITLE
how to build ?

### ISSUE THREAD

**Issue by thomasleveil** [mariusmotea/qtHue#5]
Hi,

Could you document how to build from sources for the complete Qt newbs ?

**Comment by mariusmotea** [comment]
Hi,

Just install qt creator and import the project. There you have the "Play" button that automatically compile and run the application. For devices with no desktop env (raspberry pi) you need to run qmake and then make from shell while you are located in project directory.

Marius.

**Comment by thomasleveil** [comment]
Thank you for the help. 

I just installed Qt Creator 3.5.1 (Based on Qt 5.5.1) on my Linux Mint. 
But I cannot run the thing due to: `Project ERROR: Unknown module(s) in QT: quick qml`

What am I missing?

**Comment by mariusmotea** [comment]
I don't use linux mint but i believe it use apt like Ubuntu. Try to install missing modules:

`sudo apt install libqt5core5a libqt5gui5 libqt5qml5 qtdeclarative5-localstorage-plugin qml-module-qtquick-controls`

**Comment by thomasleveil** [comment]
I had to also install `qtdeclarative5-dev`, but that's it! Thank you
