### ISSUE TITLE
run qthue

### ISSUE THREAD

**Issue by ghost** [mariusmotea/qtHue#8]
Hi, thanks for your wonderfull work, really love it. I'm a bit noob in this area... how can I run the qthue interface in a raspi 2 with raspbian? I spend two hours googling it and still have no idea...

Thanks!

**Comment by mariusmotea** [comment]
Hi,

On what OS/device you want to run it?

**Comment by ghost** [comment]
I have a Raspberry 2 with Raspbian

**Comment by mariusmotea** [comment]
`sudo apt install libqt5core5a libqt5network5 libqt5qml5 libqt5gui5 libqt5quick5` then download the binary file for Raspberry, `chmod +x qtHue` and `./qtHue` to execute it.

**Comment by ghost** [comment]
For some reason the run command now works. Thank you!
