### ISSUE TITLE
Precompile for Raspberry

### ISSUE THREAD

**Issue by cyl3x** [mariusmotea/qtHue#9]
Hey,
How to "precompile" qtHue for Raspberry, because if you setup cross-compile for raspberry, you need the cross compiled folder for the libarys on your Raspberry, but you only install a few libs  and qtHue works.
I rewrite qtHue a little bit for my case (to use my own weatherstation and have a resizeable programm) and it would be nice to know how to compile for every raspberry instead use a cross compilation build that is only for one pi :)

**Comment by mariusmotea** [comment]
Hi,

I did not use cross-compile when i build this. I manually compiled qt on the raspberry pi (version 2 was at that time) and i compile it locally with qmake. If you have some improvements feel free to contribute.

**Comment by cyl3x** [comment]
Oh okay, that makes sense. Since there arent DMs, below is a link to my sourcecode. I changed a lot for my usecase, but maybe there is something that can be included in this original version :) 
Some of the major changes:
- updated libs, qt controls 2.8 instead 1.4 -> all controls are more or lesser rewritten to use 2.8
- it should have a better performance on something like a raspi
- Bridgeconnect.qml and Weather.qml together in Settings.qml as one page
- All stuff scales with the main window
- Weather informations come from my own weather station over thinkspeak.com
- UI is red instead blue
- own weather page
